# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

title: Panashe's panache panacea
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Panashe, a life long learner, computer systems engineer and great wonderer of the world.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pmn.nz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anphase
github_username:  anphase

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-sass-converter

# Feed settings
feed:
  path: /feed.xml

# SEO settings
twitter:
  username: anphase
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Kramdown settings
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  math_engine: mathjax

# Sass settings
sass:
  style: compressed
  sourcemap: never

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  books:
    output: true
    permalink: /books/:path/

# Pagination v2 settings
pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'title'
  sort_reverse: false
